global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orders-service'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'tickets-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'order-processor'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'order-processor-2'
    static_configs:
      - targets: ['host.docker.internal:9101']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9200']
